### ISSUE TITLE
How can I remove the blue line on tabs?

### ISSUE THREAD

**Issue by tapir** [passivestar/godot-minimal-theme#1]
Superb work! I would like to get rid of the blue line on tab bar for the active tab. Is it possible to do that?

**Comment by passivestar** [comment]
Thank you!

You can do it by opening the theme in godot and adding an override for `tab_selected` on `TabContainer`

<img width="827" alt="image" src="https://github.com/passivestar/godot-minimal-theme/assets/60579014/515f3361-043c-445d-b0ae-9ca9f0ea1f32">

Closing because this isn't an issue with the theme
