### ISSUE TITLE
Light Theme Alternative

### ISSUE THREAD

**Issue by Olaf-007** [passivestar/godot-minimal-theme#10]
I love this theme and I am using it ever since I discovered it. 
However, I am a big fan of switich between light/dark mode during day/night (and there is an upcoming feature called "auto theme switch").
The current theme does not work well when forced with a bright base color. 
So here is the suggestion: It would be awesome to have your theme support light colors, too.

**Comment by passivestar** [comment]
Hi!

Godot has very limiting theming capabilities, the default theme only works relatively well in different situations because it's generated in C++. All values that you touch in your own theme become hardcoded (there are no variables or anything like that). This is the reason that to make the theme work for both regular and hidpi displays I need to maintain 2 versions of it, and doing that involves manually editing one of the files. Supporting a light theme would not only mean designing it, but it will also increase the amount of theme files that I need to support to 4

One possible solution to this would be to write a generator with support for variables that will generate the variations automatically. But writing it is additional work in itself, not to mention that it will make it harder to work on the theme in the editor

Given how limiting godot theming is I believe it is better to improve theming on the engine side first. When there's support for variables and partial styleboxes in godot themes maybe I'll consider the light theme

**Comment by Olaf-007** [comment]
That sounds reasonable. I will continue using your dark theme then, it really pulls me into the engine.

**Comment by passivestar** [comment]
This is now fixed in 2.0.0, choosing the light color preset regenerates the theme. There are some things that might need to be fixed on the engine side, but it works as well as godot's own light theme, so I'm closing this as completed. I'm currently writing a blog post to explain 2.0.0 in detail
