### ISSUE TITLE
Breakpoints in Debugger have extra margin

### ISSUE THREAD

**Issue by hsvfan-jan** [passivestar/godot-minimal-theme#14]
Hi, thanks for your great-looking theme!
While debugging I noticed the breakpoints somehow get shifted a bit too much down compared to the default theme.
<img width="306" alt="Screenshot 2024-09-27 at 17 18 49" src="https://github.com/user-attachments/assets/c3ebb583-bd0a-4ed4-b7a2-d53f0c4de254">
<img width="244" alt="Screenshot 2024-09-27 at 17 29 31" src="https://github.com/user-attachments/assets/99265a82-fb6b-479a-8a2b-a6c6499ca3a6">

Since it's extremely hidden in the default anyway when opening the debugger, this might be due to some issue on Godot's side, though? Not sure. If so, I'll open a bug issue there
<img width="997" alt="Screenshot 2024-09-27 at 17 18 33" src="https://github.com/user-attachments/assets/a64ac099-6700-4883-9506-5e2709f1a480">

**Comment by passivestar** [comment]
That's because the text input is much higher in the default theme, I had to make it smaller to fit more inputs into the inspector to make it easier to work on resources with a lot of data. In godot however that means that all of the text inputs in the editor get smaller, there's no way to style them separately

In 4.4 if my PR to be able to add backgrounds to sidebars in themes gets merged breakpoints will get its background panel back, maybe it'll make it somewhat more acceptable:

<img width="574" alt="image" src="https://github.com/user-attachments/assets/fa3294d7-8809-4f84-b0fd-7592246121ee"><br>

Godot has very rigid theming so a lot of compromises like this have to be made

**Comment by hsvfan-jan** [comment]
Yes, with https://github.com/godotengine/godot/pull/97884 merged this issue can be closed :)

**Comment by passivestar** [comment]
The PR is now merged and the latest theme version has secondary list panels. Wait for the next godot dev snapshot
